_merge: deep

# Javascripts
animation: false
bootstrap:
  carousel: false
  collapse: false
  dropdown: false
  modal: true
  offcanvas: false
  tooltip: false
carousel: false
map: false
parallax:
  enable: true
  cover: -4
  video: 0
  heading: 0

# Images
image:
  retina:
    desktop: true
hero:
  cover: 1600x800
  cover_mobile: 360x700
blocks:
  editorial:
    desktop: 720x1054
    mobile: 375x469

# Admin
admin:

  # Config
  cms: pagescms
  nested:
    depth: 0
  auth:
    netlify_identity: false
  media:
    audio_folders: false
    pdf_folders: false

  # Collections
  collections:
    indexes:
      enable: false
    config:
      files:
        - nav-primary
        - nav-legal
        # - nav-social 
        # - footer 
        - seo
    pages:
      fields:
        - draft
        - title_page
        - description
        - hero
        - blocks

  # Blocks
  blocks:
    enable:
      - editorial
      - form
      - paragraph
      - title
    editorial:
      - direction
      - surtitle
      - title
      - text_markdown
      - image
    form:
      - heading
      - grid 
      - offset
      - name 
      - submit 
      - form_items
    title:
      - heading
      - image
      - video
  
  # Fields
  fields:
    cta:
      - text
      - url
      - is_blank
    hero:
      - title
      - text_markdown
      - video
      - video_modal
    links:
      - title 
      - url
      - is_blank
    video:
      - is_background
      - video_mp4
      - video_webm
      - video_mp4_mobile
      - video_webm_mobile
    video_modal:
      - text
      - video_mp4
      - video_webm
      - video_mp4_mobile
      - video_webm_mobile